In [3]:
import pandas as pd
import os
from pathlib import Path
import json

In [4]:
BASE_PATH = Path("C:/Users/sumit/OneDrive/Documents/Data_analytics_project/PhonePe/data")
def load_json_files(base_dir):
    json_files = []
    for root,files in os.walk(base_dir):
        for file in files:
            if file.endswith('.json'):
                json_files.append(os.path.join(root, file))
    return json_files

In [5]:
# Aggregate user data
agg_tr_file = []

for state in (BASE_PATH / "aggregated" / "user" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                userData = data.get('data', {}).get('usersByDevice')
                if userData:
                    for entry in userData:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "Brand": entry.get('brand', 'Unknown'),
                            "Count": entry.get('count', 0),
                            "Percentage": entry.get('percentage', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "Brand": None,
                        "Count": None,
                        "Percentage": None
                    })
                
df_agg_user = pd.DataFrame(agg_tr_file)
df_agg_user.head()

                       State  Year Quarter    Brand   Count  Percentage
0  andaman-&-nicobar-islands  2018       1   Xiaomi  1665.0    0.247033
1  andaman-&-nicobar-islands  2018       1  Samsung  1445.0    0.214392
2  andaman-&-nicobar-islands  2018       1     Vivo   982.0    0.145697
3  andaman-&-nicobar-islands  2018       1     Oppo   501.0    0.074332
4  andaman-&-nicobar-islands  2018       1  OnePlus   332.0    0.049258

In [6]:
# Aggregate transactional data
agg_tr_file = []

for state in (BASE_PATH / "aggregated" / "transaction" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                tran_data = data.get('data', {}).get('transactionData')
                if tran_data:
                    for entry in tran_data:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "Transaction_type": entry.get('name'),
                            "Transaction_count": entry.get('paymentInstruments')[0].get('count', 0),
                            "Total_amount": entry.get('paymentInstruments')[0].get('amount', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "Transaction_type": None,
                        "Transaction_count": None,
                        "Total_amount": None
                    })
df_agg_txn = pd.DataFrame(agg_tr_file)
df_agg_txn.head()

,State,Year,Quarter,Transaction_type,Transaction_count,Total_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05

In [7]:
# Aggregate Insurance data
agg_tr_file = []

for state in (BASE_PATH / "aggregated" / "insurance" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                ins_data = data.get('data', {}).get('transactionData')
                if ins_data:
                    for entry in ins_data:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "Insurance_type": entry.get('name'),
                            "Insurance_count": entry.get('paymentInstruments')[0].get('count', 0),
                            "Total_amount": entry.get('paymentInstruments')[0].get('amount', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "Insurance_type": None,
                        "Insurance_count": None,
                        "Total_amount": None
                    })

agg_tr_df = pd.DataFrame(agg_tr_file)
agg_tr_df.head()

,State,Year,Quarter,Insurance_type,Insurance_count,Total_amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6.0,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41.0,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124.0,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225.0,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137.0,181504.0

In [8]:
# Load map transactional data
agg_tr_file = []

for state in (BASE_PATH / "map" /"transaction" / "hover" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                tran_data = data.get('data', {}).get('hoverDataList')
                if tran_data:
                    for entry in tran_data:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "District": entry.get('name'),
                            "Transaction_count": entry.get('metric')[0].get('count', 0),
                            "Total_amount": entry.get('metric')[0].get('amount', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "District": None,
                        "Transaction_count": None,
                        "Total_amount": None
                    })
df_map_txn = pd.DataFrame(agg_tr_file)
df_map_txn.head()

,State,Year,Quarter,District,Transaction_count,Total_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07

In [9]:
# Aggregate user data
agg_tr_file = []

for state in (BASE_PATH / "map" / "user" / "hover" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                userData = data.get('data', {}).get('hoverData')
                if userData:
                    for entry in userData:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "District": entry,
                            "Register_users": userData[entry].get('registeredUsers', 0),
                            "App_opens": userData[entry].get('appOpens', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "District": None,
                        "Register_users": None,
                        "App_opens": None
                    })
                
df_map_user = pd.DataFrame(agg_tr_file)
df_map_user.head()

,State,Year,Quarter,District,Register_users,App_opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0

In [10]:
# Load map insurance data

In [11]:
# Load top transaction data - district level
agg_tr_file = []

for state in (BASE_PATH / "top" /"transaction" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                tran_data = data.get('data', {}).get('districts')
                if tran_data:
                    for entry in tran_data:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "District": entry.get('entityName'),
                            "Transaction_count": entry.get('metric').get('count', 0),
                            "Total_amount": entry.get('metric').get('amount', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "District": None,
                        "Transaction_count": None,
                        "Total_amount": None

                    })
df_top_txn_dis = pd.DataFrame(agg_tr_file)
df_top_txn_dis.head()

,State,Year,Quarter,District,Transaction_count,Total_amount
0,andaman-&-nicobar-islands,2018,1,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,2,south andaman,9395,2.394824e+07
4,andaman-&-nicobar-islands,2018,2,nicobars,1120,3.072437e+06

In [12]:
# Load top transaction data - Pincode level
agg_tr_file = []

for state in (BASE_PATH / "top" /"transaction" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                tran_data = data.get('data', {}).get('pincodes')
                if tran_data:
                    for entry in tran_data:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "Pincode": entry.get('entityName'),
                            "Transaction_count": entry.get('metric').get('count', 0),
                            "Total_amount": entry.get('metric').get('amount', 0)
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "District": None,
                        "Transaction_count": None,
                        "Total_amount": None

                    })
df_top_txn_pin = pd.DataFrame(agg_tr_file)
df_top_txn_pin.head()

,State,Year,Quarter,Pincode,Transaction_count,Total_amount
0,andaman-&-nicobar-islands,2018,1,744101,1622,2.769298e+06
1,andaman-&-nicobar-islands,2018,1,744103,1223,2.238042e+06
2,andaman-&-nicobar-islands,2018,1,744102,969,3.519060e+06
3,andaman-&-nicobar-islands,2018,1,744105,685,1.298561e+06
4,andaman-&-nicobar-islands,2018,1,744104,340,1.039715e+06

In [13]:
# Load top user data - district level
agg_tr_file = []

for state in (BASE_PATH / "top" / "user" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                userData = data.get('data', {}).get('districts')
                if userData:
                    for entry in userData:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "District": entry.get('name'),
                            "Register_users": entry.get('registeredUsers', 0),
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "District": None,
                        "Register_users": None,
                    })
                
df_top_user_dis = pd.DataFrame(agg_tr_file)
df_top_user_dis.head()

,State,Year,Quarter,District,Register_users
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911

In [14]:
# Load top user data - pincodes level
agg_tr_file = []

for state in (BASE_PATH / "top" / "user" / "country" / "india" / "state").iterdir():
    for year in state.iterdir():
        for quarter in year.iterdir():
            with open(quarter, 'r') as f:
                data = json.load(f)
                userData = data.get('data', {}).get('pincodes')
                if userData:
                    for entry in userData:
                        agg_tr_file.append({
                            "State": state.name,
                            "Year": str(year.name),
                            "Quarter": quarter.stem,
                            "Pincode": entry.get('name'),
                            "Register_users": entry.get('registeredUsers', 0),
                        })
                else:
                    agg_tr_file.append({
                        "State": state.name,
                        "Year": str(year.name),
                        "Quarter": quarter.stem,
                        "Pincode": None,
                        "Register_users": None,
                    })
                
df_top_user_pin = pd.DataFrame(agg_tr_file)
df_top_user_pin.head()

                       State  Year Quarter Pincode  Register_users
0  andaman-&-nicobar-islands  2018       1  744103            1608
1  andaman-&-nicobar-islands  2018       1  744101            1108
2  andaman-&-nicobar-islands  2018       1  744105            1075
3  andaman-&-nicobar-islands  2018       1  744102            1006
4  andaman-&-nicobar-islands  2018       1  744104             272

# Preprocessing

In [15]:
def clean_data(df, number_cols, string_cols):
    #remove duplicates
    df = df.copy()
    df = df.drop_duplicates()

    #remove whitespace from string columns with replace space the _
    for col in string_cols:
        df[col] = df[col].str.strip().str.replace(" ", "_") 
    # fill missing values in number columns with 0
    if number_cols:
        for col in number_cols:
            if col in df.columns:
                df[col] = df[col].fillna(0)

    # fill missing values in string columns with "Unknown"
    if string_cols:
        for col in string_cols:
            if col in df.columns:
                df[col] = df[col].fillna("Unknown")
                
    # Removing invalid values (negative amount/count) 
    if number_cols:  
        for col in number_cols:
            if col in df.columns:
                df[col] = df[col].apply(lambda x: x if x >= 0 else 0)


    return df

In [20]:
# clean all dataframs
df_agg_txn = clean_data(df_agg_txn, ["Transaction_count", "Total_amount"], ["State","Year","Quarter","Transaction_type"])
df_agg_user = clean_data(df_agg_user, ["Count","Percentage"], ["State", "Brand","Year","Quarter"])
df_map_txn = clean_data(df_map_txn, ["Transaction_count", "Total_amount"], ["State", "District", "Year","Quarter"])
df_map_user = clean_data(df_map_user, ["App_opens", "Registered_users"], ["State", "District", "Year","Quarter"])
df_top_txn_dis = clean_data(df_top_txn_dis, ["Transaction_count", "Total_amount"], ["State", "District", "Year","Quarter"])
df_top_txn_pin = clean_data(df_top_txn_pin, ["Transaction_count", "Total_amount"], ["State", "Pincode", "Year","Quarter"])
df_top_user_dis = clean_data(df_top_user_dis, ["Register_users"], ["State", "District", "Year","Quarter"])
df_top_user_pin = clean_data(df_top_user_pin, ["Register_users"], ["State", "Pincode"])

In [21]:
# Export cleaned data to csv in cleaned_data folder
output_dir = BASE_PATH / "cleaned_data"
output_dir.mkdir(exist_ok=True)
df_agg_txn.to_csv(output_dir / "agg_txn.csv", index=False)
df_agg_user.to_csv(output_dir / "agg_user.csv", index=False)
df_map_txn.to_csv(output_dir / "map_txn.csv", index=False)
df_map_user.to_csv(output_dir / "map_user.csv", index=False)
df_top_txn_dis.to_csv(output_dir / "top_txn_dis.csv", index=False)
df_top_txn_pin.to_csv(output_dir / "top_txn_pin.csv", index=False)
df_top_user_dis.to_csv(output_dir / "top_user_dis.csv", index=False)
df_top_user_pin.to_csv(output_dir / "top_user_pin.csv", index=False)

In [22]:
# creating sqlite database and inserting cleaned data into it
import sqlite3
conn = sqlite3.connect('phonepe_data.db')
df_agg_txn.to_sql('agg_txn', conn, if_exists='replace', index=False)
df_agg_user.to_sql('agg_user', conn, if_exists='replace', index=False)
df_map_txn.to_sql('map_txn', conn, if_exists='replace', index=False)
df_map_user.to_sql('map_user', conn, if_exists='replace', index=False)
df_top_txn_dis.to_sql('top_txn_dis', conn, if_exists='replace', index=False)
df_top_txn_pin.to_sql('top_txn_pin', conn, if_exists='replace', index=False)
df_top_user_dis.to_sql('top_user_dis', conn, if_exists='replace', index=False)
df_top_user_pin.to_sql('top_user_pin', conn, if_exists='replace', index=False)

10000